Algoritmo "semnome"

Var
 placa: caractere
 cont: inteiro
 valor, soma: real

Inicio

      para cont de 1 ate 4 faca
           escreval ("Informe a placa do veículo ", cont)
           leia(placa)
           escreval ("Informe o valor do veículo ", cont)
           leia(valor)
           soma <- soma + valor
           escreval("soma parcial ", soma)
    fimpara
       escreval("soma final ", soma)
       escreval("media ", soma/4)

Fimalgoritmo